using R4PDF.Fluent;
using R4PDF.Fluent.Themes;

namespace R4PDF.Tests;

public class FluentPdfGenerationTests : IDisposable
{
    private readonly string _outputDir;

    public FluentPdfGenerationTests()
    {
        _outputDir = Path.GetFullPath(
            Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "generated-pdfs"));
        Directory.CreateDirectory(_outputDir);
    }

    public void Dispose()
    {
    }

    private string OutputPath(string name)
    {
        return Path.Combine(_outputDir, name);
    }

    private void AssertValidPdf(string path)
    {
        Assert.True(File.Exists(path), $"PDF was not created at: {path}");
        var bytes = File.ReadAllBytes(path);
        Assert.True(bytes.Length > 100, "PDF file is suspiciously small");
        Assert.Equal((byte)'%', bytes[0]);
        Assert.Equal((byte)'P', bytes[1]);
        Assert.Equal((byte)'D', bytes[2]);
        Assert.Equal((byte)'F', bytes[3]);
    }

    // ── 1. Hello World (Default theme) ───────────────────────────────────

    [Fact]
    public void Fluent_HelloWorld_DefaultTheme()
    {
        var path = OutputPath("fluent-01-hello-world.pdf");

        Pdf.Create()
            .WithTheme(PdfTheme.Default)
            .WithMetadata(m => m.Title("Hello World - Fluent API"))
            .AddPage(page => page
                .Body(b => b
                    .Heading1("Hello, World!")
                    .Text("This PDF was generated using the R4PDF fluent API.")
                    .Spacer()
                    .MutedText("Generated by R4PDF Fluent Builder")))
            .GenerateToFile(path);

        AssertValidPdf(path);
    }

    // ── 2. Dark Theme Document ───────────────────────────────────────────

    [Fact]
    public void Fluent_DarkTheme()
    {
        var path = OutputPath("fluent-02-dark-theme.pdf");

        Pdf.Create()
            .WithTheme(PdfTheme.Dark)
            .WithMetadata(m => m.Title("Dark Theme Demo"))
            .AddPage(page => page
                .Body(b => b
                    .Heading1("Dark Theme")
                    .Heading2("A Modern Look")
                    .Spacer()
                    .Paragraph(
                        "This document uses the Dark theme. All text colors, headings, and table styles are automatically applied from the theme definition. No manual color specification needed.")
                    .Spacer()
                    .AccentText("This is accented text — stands out!")
                    .MutedText("This is muted text — subtle.")
                    .Spacer()
                    .Table(t => t
                        .Column("Feature", "50%")
                        .Column("Status", "25%", Alignments.Center)
                        .Column("Score", "25%", Alignments.Right)
                        .Row("Dark Mode", "Active", "95%")
                        .Row("Contrast", "High", "88%")
                        .Row("Readability", "Good", "92%"))))
            .GenerateToFile(path);

        AssertValidPdf(path);
    }

    // ── 3. Modern Theme Document ─────────────────────────────────────────

    [Fact]
    public void Fluent_ModernTheme()
    {
        var path = OutputPath("fluent-03-modern-theme.pdf");

        Pdf.Create()
            .WithTheme(PdfTheme.Modern)
            .WithMetadata(m => m.Title("Modern Theme Demo"))
            .AddPage(page => page
                .Header(h => h.Text("Modern Theme Showcase"))
                .Body(b => b
                    .Heading1("Modern Design")
                    .Heading2("Clean & Minimal")
                    .Heading3("Section Details")
                    .Spacer()
                    .Paragraph(
                        "The Modern theme features wider margins, larger heading sizes, and increased line height for a spacious reading experience. It's ideal for documents that prioritize readability and visual hierarchy.")
                    .Spacer()
                    .Line()
                    .Spacer()
                    .Text("Key Metrics")
                    .Table(t => t
                        .Column("Metric", "40%")
                        .Column("Q3", "20%", Alignments.Right)
                        .Column("Q4", "20%", Alignments.Right)
                        .Column("Change", "20%", Alignments.Right)
                        .Row("Revenue", "$8.2M", "$10.1M", "+23%")
                        .Row("Users", "45,000", "62,000", "+38%")
                        .Row("NPS", "72", "81", "+12.5%")))
                .Footer(f => f.CaptionText("Page {pageNumber} of {pageCount}")))
            .GenerateToFile(path);

        AssertValidPdf(path);
    }

    // ── 4. Custom Theme ──────────────────────────────────────────────────

    [Fact]
    public void Fluent_CustomTheme()
    {
        var path = OutputPath("fluent-04-custom-theme.pdf");

        var brandTheme = new PdfThemeBuilder(PdfTheme.Default)
            .Heading1(s =>
            {
                s.Color = "#8B0000";
                s.FontSize = 26;
            })
            .Heading2(s => { s.Color = "#A52A2A"; })
            .Accent(s => { s.Color = "#FF4500"; })
            .Table(t =>
            {
                t.HeaderBackgroundColor = "#8B0000";
                t.AlternateColor = "#FFF5F5";
            })
            .Line(l => l.Color = "#8B0000")
            .Build();

        Pdf.Create()
            .WithTheme(brandTheme)
            .WithMetadata(m => m.Title("Custom Brand Theme"))
            .AddPage(page => page
                .Body(b => b
                    .Heading1("Custom Brand Theme")
                    .Heading2("Red & Professional")
                    .Spacer()
                    .Paragraph(
                        "This document uses a custom theme built on top of the Default theme. The heading colors, table header, and line colors have been overridden to match a brand palette.")
                    .Spacer()
                    .AccentText("Accent text in brand orange!")
                    .Spacer()
                    .Table(t => t
                        .Column("Department", "40%")
                        .Column("Budget", "30%", Alignments.Right)
                        .Column("Spent", "30%", Alignments.Right)
                        .Row("Engineering", "$500,000", "$480,000")
                        .Row("Marketing", "$300,000", "$320,000")
                        .Row("Operations", "$200,000", "$190,000"))
                    .Spacer()
                    .Line()
                    .MutedText("Confidential — Internal Use Only")))
            .GenerateToFile(path);

        AssertValidPdf(path);
    }

    // ── 5. Invoice (Fluent API) ──────────────────────────────────────────

    [Fact]
    public void Fluent_Invoice()
    {
        var path = OutputPath("fluent-05-invoice.pdf");

        Pdf.Create()
            .WithTheme(PdfTheme.Default)
            .WithMetadata(m => m.Title("Invoice #INV-2024-0042").Author("Acme Corp"))
            .AddPage(page => page
                .Header(h => h
                    .Height("40mm")
                    .Text("Acme Software Solutions", o =>
                    {
                        o.FontSize = 24;
                        o.FontWeight = FontWeights.Bold;
                        o.Color = "#003366";
                    })
                    .Text("123 Innovation Drive, Suite 500, San Francisco, CA 94105", o =>
                    {
                        o.FontSize = 10;
                        o.Color = "#666666";
                    })
                    .Text("(415) 555-0199  |  billing@acmesoftware.com", o =>
                    {
                        o.FontSize = 10;
                        o.Color = "#666666";
                    })
                    .Line())
                .Body(b => b
                    .Text("INVOICE", o =>
                    {
                        o.FontSize = 20;
                        o.FontWeight = FontWeights.Bold;
                        o.Color = "#003366";
                    })
                    .Spacer()
                    .Text("Invoice #: INV-2024-0042")
                    .Text("Date: March 13, 2026")
                    .Text("Due Date: April 12, 2026")
                    .Spacer()
                    .Heading2("Bill To:")
                    .Text("TechVentures Inc.")
                    .Text("456 Market Street, Floor 12, New York, NY 10001")
                    .Spacer()
                    .Table(t => t
                        .Column("Description", "40%")
                        .Column("Hours", "15%", Alignments.Center)
                        .Column("Rate", "15%", Alignments.Right)
                        .Column("Amount", "15%", Alignments.Right)
                        .Column("Tax", "15%", Alignments.Right)
                        .Row("Frontend Development", "80", "$140", "$11,200", "$896")
                        .Row("Backend API", "60", "$150", "$9,000", "$720")
                        .Row("Database Design", "20", "$160", "$3,200", "$256")
                        .Row("UI/UX Design", "40", "$120", "$4,800", "$384")
                        .Row("QA Testing", "30", "$110", "$3,300", "$264"))
                    .Spacer()
                    .Line()
                    .Text("Subtotal: $31,500.00", o => o.Alignment = Alignments.Right)
                    .Text("Tax (8%): $2,520.00", o => o.Alignment = Alignments.Right)
                    .Line(o => o.StrokeWidth = "2pt")
                    .Text("TOTAL DUE: $34,020.00", o =>
                    {
                        o.FontSize = 14;
                        o.FontWeight = FontWeights.Bold;
                        o.Color = "#003366";
                        o.Alignment = Alignments.Right;
                    }))
                .Footer(f => f
                    .Line()
                    .CaptionText("Thank you for your business!")
                    .CaptionText("Page {pageNumber} of {pageCount}  |  Acme Software Solutions")))
            .GenerateToFile(path);

        AssertValidPdf(path);
    }

    // ── 6. Multi-page Report ─────────────────────────────────────────────

    [Fact]
    public void Fluent_MultiPageReport()
    {
        var path = OutputPath("fluent-06-multipage-report.pdf");

        Pdf.Create()
            .WithTheme(PdfTheme.Modern)
            .WithMetadata(m => m.Title("Q4 2024 Report").Author("Analytics Team"))
            // Cover page
            .AddPage(p => p
                .Body(b => b
                    .Spacer().Spacer().Spacer()
                    .Rectangle(o =>
                    {
                        o.FillColor = "#2C3E50";
                        o.Width = "170mm";
                        o.Height = "3mm";
                    })
                    .Spacer()
                    .Heading1("Quarterly Report")
                    .Text("Q4 2024  |  October - December", o =>
                    {
                        o.FontSize = 16;
                        o.Color = "#888888";
                    })
                    .Spacer().Spacer()
                    .MutedText("Prepared by Analytics Team")
                    .MutedText("January 2025")))
            // Content page
            .AddPage(p => p
                .Header(h => h.MutedText("Q4 2024 Report  |  Confidential"))
                .Body(b => b
                    .Heading1("1. Revenue Performance")
                    .Line()
                    .Spacer()
                    .Paragraph(
                        "Revenue growth exceeded targets across all business units. Total Q4 revenue reached $12.8M, a 23% increase year-over-year.")
                    .Spacer()
                    .Table(t => t
                        .Column("Revenue Stream", "35%")
                        .Column("Q3", "16%", Alignments.Right)
                        .Column("Q4", "16%", Alignments.Right)
                        .Column("Change", "16%", Alignments.Right)
                        .Column("% Total", "17%", Alignments.Right)
                        .Row("SaaS Subscriptions", "$4.2M", "$5.1M", "+21%", "39.8%")
                        .Row("Enterprise Licenses", "$2.8M", "$3.4M", "+21%", "26.6%")
                        .Row("Professional Services", "$1.5M", "$2.0M", "+33%", "15.6%")
                        .Row("Support", "$1.1M", "$1.3M", "+18%", "10.2%"))
                    .Spacer()
                    .AccentText("Total Q4 Revenue: $12.8M (+23% YoY)"))
                .Footer(f => f.CaptionText("Page {pageNumber} of {pageCount}  |  Confidential")))
            // KPIs page
            .AddPage(p => p
                .Header(h => h.MutedText("Q4 2024 Report  |  Confidential"))
                .Body(b => b
                    .Heading1("2. Key Performance Indicators")
                    .Line()
                    .Spacer()
                    .Table(t => t
                        .Column("KPI", "35%")
                        .Column("Target", "16%", Alignments.Right)
                        .Column("Actual", "16%", Alignments.Right)
                        .Column("Status", "16%", Alignments.Center)
                        .Column("Trend", "17%", Alignments.Center)
                        .Row("MRR", "$4.2M", "$4.5M", "Exceeded", "Up")
                        .Row("CAC", "$1,200", "$980", "Exceeded", "Down")
                        .Row("Churn Rate", "< 3%", "2.4%", "Exceeded", "Down")
                        .Row("NPS Score", "> 70", "82", "Exceeded", "Up")
                        .Row("Uptime", "99.9%", "99.97%", "Exceeded", "Stable"))
                    .Spacer()
                    .Paragraph(
                        "All tracked KPIs exceeded targets. Customer acquisition cost dropped 18% below target due to improved marketing efficiency."))
                .Footer(f => f.CaptionText("Page {pageNumber} of {pageCount}  |  Confidential")))
            .GenerateToFile(path);

        AssertValidPdf(path);
    }

    // ── 7. Generate to byte[] ────────────────────────────────────────────

    [Fact]
    public void Fluent_GenerateToBytes()
    {
        var bytes = Pdf.Create()
            .WithTheme(PdfTheme.Default)
            .AddPage(p => p.Body(b => b.Heading1("Byte array test")))
            .Generate();

        Assert.True(bytes.Length > 100);
        Assert.Equal((byte)'%', bytes[0]);
        Assert.Equal((byte)'P', bytes[1]);
    }

    // ── 8. Generate to stream ────────────────────────────────────────────

    [Fact]
    public void Fluent_GenerateToStream()
    {
        using var stream = new MemoryStream();

        Pdf.Create()
            .WithTheme(PdfTheme.Default)
            .AddPage(p => p.Body(b => b.Text("Stream test")))
            .GenerateToStream(stream);

        Assert.True(stream.Length > 100);
        stream.Position = 0;
        Assert.Equal((byte)'%', stream.ReadByte());
        Assert.Equal((byte)'P', stream.ReadByte());
    }

    // ── 9. No theme (bare bones) ─────────────────────────────────────────

    [Fact]
    public void Fluent_NoTheme_StillWorks()
    {
        var path = OutputPath("fluent-09-no-theme.pdf");

        Pdf.Create()
            .AddPage(p => p.Body(b => b
                .Text("No theme applied")
                .Text("Using default renderer settings")))
            .GenerateToFile(path);

        AssertValidPdf(path);
    }

    // ── 10. PdfGenerator.Generate(PdfTemplate) directly ──────────────────

    [Fact]
    public void PdfGenerator_AcceptsPdfTemplate()
    {
        var template = Pdf.Create()
            .WithTheme(PdfTheme.Default)
            .WithMetadata(m => m.Title("Direct Template"))
            .AddPage(p => p.Body(b => b.Heading1("Direct").Paragraph("Content")))
            .Build();

        var generator = new PdfGenerator();
        var bytes = generator.Generate(template);

        Assert.True(bytes.Length > 100);
        Assert.Equal((byte)'%', bytes[0]);
    }
}