namespace R4PDF.Tests;

/// <summary>
///     Generates real PDF files to the output directory so you can open and inspect them.
///     Output directory: tests/R4PDF.Tests/generated-pdfs/
/// </summary>
public class RealPdfGenerationTests : IDisposable
{
    private readonly PdfGenerator _generator = new();
    private readonly string _outputDir;

    public RealPdfGenerationTests()
    {
        // Output to a fixed directory relative to the project root so it's easy to find
        _outputDir = Path.GetFullPath(
            Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "generated-pdfs"));
        Directory.CreateDirectory(_outputDir);
    }

    public void Dispose()
    {
        /* output dir intentionally kept */
    }

    private string OutputPath(string name)
    {
        return Path.Combine(_outputDir, name);
    }

    private void GenerateAndAssert(string template, string fileName, string? data = null)
    {
        var path = OutputPath(fileName);
        _generator.GenerateToFile(template, data, path);

        Assert.True(File.Exists(path), $"PDF was not created at: {path}");
        var bytes = File.ReadAllBytes(path);
        Assert.True(bytes.Length > 100, "PDF file is suspiciously small");
        // Verify PDF header magic bytes
        Assert.Equal((byte)'%', bytes[0]);
        Assert.Equal((byte)'P', bytes[1]);
        Assert.Equal((byte)'D', bytes[2]);
        Assert.Equal((byte)'F', bytes[3]);
    }

    // ── 1. Basic Text & Styles ──────────────────────────────────────────────

    [Fact]
    public void Generate_HelloWorld()
    {
        var template = """
                       {
                           "metadata": { "title": "Hello World Test" },
                           "settings": { "pageSize": "A4" },
                           "pages": [{
                               "body": {
                                   "elements": [
                                       { "type": "text", "text": "Hello, World!", "fontSize": 36, "fontWeight": "bold", "color": "#000000" },
                                       { "type": "text", "text": "This is a basic PDF generated from a JSON template.", "fontSize": 14, "color": "#555555" },
                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "Generated by R4PDF", "fontSize": 10, "color": "#999999" }
                                   ]
                               }
                           }]
                       }
                       """;

        GenerateAndAssert(template, "01-hello-world.pdf");
    }

    // ── 2. Rich Styled Document ─────────────────────────────────────────────

    [Fact]
    public void Generate_StyledDocument()
    {
        var template = """
                       {
                           "metadata": { "title": "Styled Document" },
                           "styles": {
                               "h1": { "fontSize": 28, "fontWeight": "bold", "color": "#1a1a2e" },
                               "h2": { "fontSize": 18, "fontWeight": "bold", "color": "#16213e" },
                               "h3": { "fontSize": 14, "fontWeight": "bold", "color": "#0f3460" },
                               "body": { "fontSize": 11, "color": "#333333", "lineHeight": 1.6 },
                               "accent": { "fontSize": 11, "fontWeight": "bold", "color": "#e94560" },
                               "muted": { "fontSize": 9, "color": "#888888" }
                           },
                           "pages": [{
                               "body": {
                                   "elements": [
                                       { "type": "text", "text": "Typography & Style Showcase", "style": "h1" },
                                       { "type": "line", "color": "#1a1a2e", "strokeWidth": "2pt" },
                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "Heading Level 2", "style": "h2" },
                                       { "type": "text", "text": "Heading Level 3", "style": "h3" },
                                       { "type": "text", "text": "" },
                                       {
                                           "type": "paragraph",
                                           "content": "This paragraph demonstrates body text styling with a comfortable line height of 1.6. The text should wrap naturally across the available width of the page, respecting the margins set in the document settings. Good typography makes documents pleasant to read.",
                                           "style": "body"
                                       },
                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "This is accented text — great for highlighting important info!", "style": "accent" },
                                       { "type": "text", "text": "This is muted text — for less important details.", "style": "muted" },
                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "Font Sizes Demo", "style": "h2" },
                                       { "type": "text", "text": "8pt text", "fontSize": 8 },
                                       { "type": "text", "text": "10pt text", "fontSize": 10 },
                                       { "type": "text", "text": "12pt text (default)", "fontSize": 12 },
                                       { "type": "text", "text": "16pt text", "fontSize": 16 },
                                       { "type": "text", "text": "20pt text", "fontSize": 20 },
                                       { "type": "text", "text": "28pt text", "fontSize": 28 },
                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "Text Alignment", "style": "h2" },
                                       { "type": "text", "text": "Left aligned (default)", "fontSize": 12, "alignment": "left" },
                                       { "type": "text", "text": "Center aligned", "fontSize": 12, "alignment": "center" },
                                       { "type": "text", "text": "Right aligned", "fontSize": 12, "alignment": "right" }
                                   ]
                               }
                           }]
                       }
                       """;

        GenerateAndAssert(template, "02-styled-document.pdf");
    }

    // ── 3. Full Invoice with Data Binding ───────────────────────────────────

    [Fact]
    public void Generate_Invoice()
    {
        var template = """
                       {
                           "metadata": { "title": "Invoice #INV-2024-0042", "author": "Acme Corp" },
                           "settings": {
                               "pageSize": "A4",
                               "margins": { "top": "20mm", "bottom": "20mm", "left": "15mm", "right": "15mm" }
                           },
                           "styles": {
                               "companyName": { "fontSize": 24, "fontWeight": "bold", "color": "#003366" },
                               "companyAddr": { "fontSize": 10, "color": "#666666" },
                               "invoiceTitle": { "fontSize": 20, "fontWeight": "bold", "color": "#003366" },
                               "label": { "fontSize": 10, "fontWeight": "bold", "color": "#333333" },
                               "value": { "fontSize": 10, "color": "#000000" },
                               "total": { "fontSize": 14, "fontWeight": "bold", "color": "#003366", "alignment": "right" },
                               "footerText": { "fontSize": 9, "color": "#999999", "alignment": "center" }
                           },
                           "pages": [{
                               "header": {
                                   "height": "45mm",
                                   "elements": [
                                       { "type": "text", "text": "${company.name}", "style": "companyName" },
                                       { "type": "text", "text": "${company.address}", "style": "companyAddr" },
                                       { "type": "text", "text": "${company.phone}  |  ${company.email}", "style": "companyAddr" },
                                       { "type": "line", "color": "#003366", "strokeWidth": "2pt" }
                                   ]
                               },
                               "body": {
                                   "elements": [
                                       { "type": "text", "text": "INVOICE", "style": "invoiceTitle" },
                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "Invoice #: ${invoice.number}", "style": "value" },
                                       { "type": "text", "text": "Date: ${invoice.date}", "style": "value" },
                                       { "type": "text", "text": "Due Date: ${invoice.dueDate}", "style": "value" },
                                       { "type": "text", "text": "Payment Terms: ${invoice.terms}", "style": "value" },
                                       { "type": "text", "text": "" },
                                       { "type": "rectangle", "fillColor": "#F8F9FA", "width": "180mm", "height": "30mm", "strokeColor": "#DEE2E6", "strokeWidth": "0.5pt" },
                                       { "type": "text", "text": "BILL TO:", "style": "label" },
                                       { "type": "text", "text": "${customer.name}", "style": "value" },
                                       { "type": "text", "text": "${customer.address}", "style": "value" },
                                       { "type": "text", "text": "${customer.email}", "style": "value" },
                                       { "type": "text", "text": "" },
                                       {
                                           "type": "table",
                                           "columns": [
                                               { "name": "Description", "width": "40%" },
                                               { "name": "Hours/Qty", "width": "15%", "alignment": "center" },
                                               { "name": "Rate", "width": "15%", "alignment": "right" },
                                               { "name": "Amount", "width": "15%", "alignment": "right" },
                                               { "name": "Tax", "width": "15%", "alignment": "right" }
                                           ],
                                           "rows": [
                                               { "cells": ["Frontend Development (React)", "80", "$140.00", "$11,200.00", "$896.00"] },
                                               { "cells": ["Backend API Development", "60", "$150.00", "$9,000.00", "$720.00"] },
                                               { "cells": ["Database Design & Optimization", "20", "$160.00", "$3,200.00", "$256.00"] },
                                               { "cells": ["UI/UX Design & Prototyping", "40", "$120.00", "$4,800.00", "$384.00"] },
                                               { "cells": ["QA Testing & Bug Fixes", "30", "$110.00", "$3,300.00", "$264.00"] },
                                               { "cells": ["DevOps & Deployment", "15", "$170.00", "$2,550.00", "$204.00"] },
                                               { "cells": ["Project Management", "25", "$130.00", "$3,250.00", "$260.00"] },
                                               { "cells": ["Documentation", "10", "$100.00", "$1,000.00", "$80.00"] }
                                           ],
                                           "headerStyle": {
                                               "backgroundColor": "#003366",
                                               "color": "#FFFFFF",
                                               "fontWeight": "bold"
                                           },
                                           "alternateRowColors": true,
                                           "alternateColor": "#F0F4F8",
                                           "borders": { "width": "0.5pt", "color": "#DEE2E6" }
                                       },
                                       { "type": "text", "text": "" },
                                       { "type": "line", "color": "#DEE2E6", "strokeWidth": "0.5pt" },
                                       { "type": "text", "text": "Subtotal: $38,300.00", "fontSize": 11, "alignment": "right" },
                                       { "type": "text", "text": "Tax (8%): $3,064.00", "fontSize": 11, "alignment": "right" },
                                       { "type": "line", "color": "#003366", "strokeWidth": "1pt" },
                                       { "type": "text", "text": "TOTAL DUE: $41,364.00", "style": "total" },
                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "" },
                                       { "type": "rectangle", "fillColor": "#F0F4F8", "width": "180mm", "height": "25mm", "strokeColor": "#DEE2E6", "strokeWidth": "0.5pt" },
                                       { "type": "text", "text": "Payment Instructions:", "style": "label" },
                                       { "type": "text", "text": "Bank: First National Bank  |  Account: 1234567890  |  Routing: 021000021", "fontSize": 9, "color": "#555555" },
                                       { "type": "text", "text": "Please include invoice number in payment reference.", "fontSize": 9, "color": "#555555" }
                                   ]
                               },
                               "footer": {
                                   "height": "20mm",
                                   "elements": [
                                       { "type": "line", "color": "#DEE2E6", "strokeWidth": "0.5pt" },
                                       { "type": "text", "text": "Thank you for your business!", "style": "footerText" },
                                       { "type": "text", "text": "Page {pageNumber} of {pageCount}  |  ${company.name}", "style": "footerText" }
                                   ]
                               }
                           }]
                       }
                       """;

        var data = """
                   {
                       "company": {
                           "name": "Acme Software Solutions",
                           "address": "123 Innovation Drive, Suite 500, San Francisco, CA 94105",
                           "phone": "(415) 555-0199",
                           "email": "billing@acmesoftware.com"
                       },
                       "invoice": {
                           "number": "INV-2024-0042",
                           "date": "March 13, 2026",
                           "dueDate": "April 12, 2026",
                           "terms": "Net 30"
                       },
                       "customer": {
                           "name": "TechVentures Inc.",
                           "address": "456 Market Street, Floor 12, New York, NY 10001",
                           "email": "accounts@techventures.io"
                       }
                   }
                   """;

        GenerateAndAssert(template, "03-invoice.pdf", data);
    }

    // ── 4. Quarterly Report with Multi-Page ─────────────────────────────────

    [Fact]
    public void Generate_QuarterlyReport()
    {
        var template = """
                       {
                           "metadata": { "title": "Q4 2024 Quarterly Report", "author": "Analytics Team" },
                           "settings": {
                               "pageSize": "A4",
                               "margins": { "top": "25mm", "bottom": "25mm", "left": "20mm", "right": "20mm" }
                           },
                           "styles": {
                               "coverTitle": { "fontSize": 32, "fontWeight": "bold", "color": "#1a1a2e" },
                               "coverSubtitle": { "fontSize": 16, "color": "#666666" },
                               "h1": { "fontSize": 22, "fontWeight": "bold", "color": "#1a1a2e" },
                               "h2": { "fontSize": 16, "fontWeight": "bold", "color": "#16213e" },
                               "body": { "fontSize": 11, "color": "#333333", "lineHeight": 1.5 },
                               "caption": { "fontSize": 9, "color": "#888888", "alignment": "center" },
                               "highlight": { "fontSize": 12, "fontWeight": "bold", "color": "#e94560" }
                           },
                           "pages": [
                               {
                                   "body": {
                                       "elements": [
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "" },
                                           { "type": "rectangle", "fillColor": "#1a1a2e", "width": "170mm", "height": "3mm" },
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "Quarterly Business Report", "style": "coverTitle" },
                                           { "type": "text", "text": "Q4 2024  |  October - December", "style": "coverSubtitle" },
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "Prepared by: Analytics & Strategy Division", "fontSize": 12, "color": "#888888" },
                                           { "type": "text", "text": "Date: January 15, 2025", "fontSize": 12, "color": "#888888" },
                                           { "type": "text", "text": "Classification: Confidential", "fontSize": 12, "color": "#e94560", "fontWeight": "bold" },
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "" },
                                           { "type": "rectangle", "fillColor": "#1a1a2e", "width": "170mm", "height": "1mm" }
                                       ]
                                   }
                               },
                               {
                                   "header": {
                                       "height": "12mm",
                                       "elements": [
                                           { "type": "text", "text": "Q4 2024 Quarterly Report  |  Confidential", "fontSize": 8, "color": "#AAAAAA" }
                                       ]
                                   },
                                   "body": {
                                       "elements": [
                                           { "type": "text", "text": "1. Executive Summary", "style": "h1" },
                                           { "type": "line", "color": "#1a1a2e", "strokeWidth": "1.5pt" },
                                           { "type": "text", "text": "" },
                                           {
                                               "type": "paragraph",
                                               "content": "Q4 2024 marked the strongest quarter in company history. Total revenue reached $12.8M, representing a 23% year-over-year increase. The company successfully launched three new product lines, expanded into two new markets, and grew the team by 45 new hires. Customer satisfaction scores reached an all-time high of 92%, while employee retention remained strong at 96%.",
                                               "style": "body"
                                           },
                                           { "type": "text", "text": "" },
                                           {
                                               "type": "paragraph",
                                               "content": "Key achievements include the successful completion of the Platform 2.0 migration, which reduced infrastructure costs by 35% while improving system reliability to 99.97% uptime. The Sales team exceeded their annual target by 18%, and the Marketing team achieved a 40% reduction in customer acquisition costs through optimized digital campaigns.",
                                               "style": "body"
                                           },
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "2. Financial Performance", "style": "h1" },
                                           { "type": "line", "color": "#1a1a2e", "strokeWidth": "1.5pt" },
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "2.1 Revenue Breakdown", "style": "h2" },
                                           {
                                               "type": "table",
                                               "columns": [
                                                   { "name": "Revenue Stream", "width": "35%" },
                                                   { "name": "Q3 2024", "width": "16%", "alignment": "right" },
                                                   { "name": "Q4 2024", "width": "16%", "alignment": "right" },
                                                   { "name": "Change", "width": "16%", "alignment": "right" },
                                                   { "name": "% of Total", "width": "17%", "alignment": "right" }
                                               ],
                                               "rows": [
                                                   { "cells": ["SaaS Subscriptions", "$4.2M", "$5.1M", "+21.4%", "39.8%"] },
                                                   { "cells": ["Enterprise Licenses", "$2.8M", "$3.4M", "+21.4%", "26.6%"] },
                                                   { "cells": ["Professional Services", "$1.5M", "$2.0M", "+33.3%", "15.6%"] },
                                                   { "cells": ["Support & Maintenance", "$1.1M", "$1.3M", "+18.2%", "10.2%"] },
                                                   { "cells": ["Training & Certification", "$0.6M", "$0.7M", "+16.7%", "5.5%"] },
                                                   { "cells": ["Other Revenue", "$0.2M", "$0.3M", "+50.0%", "2.3%"] }
                                               ],
                                               "headerStyle": { "backgroundColor": "#1a1a2e", "color": "#FFFFFF", "fontWeight": "bold" },
                                               "alternateRowColors": true,
                                               "alternateColor": "#F8F9FA",
                                               "borders": { "width": "0.5pt", "color": "#DEE2E6" }
                                           },
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "Total Q4 Revenue: $12.8M (+23% YoY)", "style": "highlight" }
                                       ]
                                   },
                                   "footer": {
                                       "height": "12mm",
                                       "elements": [
                                           { "type": "text", "text": "Page {pageNumber} of {pageCount}  |  Confidential", "style": "caption" }
                                       ]
                                   }
                               },
                               {
                                   "header": {
                                       "height": "12mm",
                                       "elements": [
                                           { "type": "text", "text": "Q4 2024 Quarterly Report  |  Confidential", "fontSize": 8, "color": "#AAAAAA" }
                                       ]
                                   },
                                   "body": {
                                       "elements": [
                                           { "type": "text", "text": "2.2 Expense Summary", "style": "h2" },
                                           {
                                               "type": "table",
                                               "columns": [
                                                   { "name": "Category", "width": "40%" },
                                                   { "name": "Budget", "width": "20%", "alignment": "right" },
                                                   { "name": "Actual", "width": "20%", "alignment": "right" },
                                                   { "name": "Variance", "width": "20%", "alignment": "right" }
                                               ],
                                               "rows": [
                                                   { "cells": ["Engineering & R&D", "$3,200,000", "$3,050,000", "-$150,000"] },
                                                   { "cells": ["Sales & Marketing", "$2,100,000", "$2,250,000", "+$150,000"] },
                                                   { "cells": ["General & Administrative", "$1,400,000", "$1,380,000", "-$20,000"] },
                                                   { "cells": ["Infrastructure & Cloud", "$800,000", "$520,000", "-$280,000"] },
                                                   { "cells": ["Customer Support", "$600,000", "$580,000", "-$20,000"] },
                                                   { "cells": ["Training & Development", "$300,000", "$310,000", "+$10,000"] }
                                               ],
                                               "headerStyle": { "backgroundColor": "#16213e", "color": "#FFFFFF", "fontWeight": "bold" },
                                               "alternateRowColors": true,
                                               "alternateColor": "#F8F9FA",
                                               "borders": { "width": "0.5pt", "color": "#DEE2E6" }
                                           },
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "3. Key Performance Indicators", "style": "h1" },
                                           { "type": "line", "color": "#1a1a2e", "strokeWidth": "1.5pt" },
                                           { "type": "text", "text": "" },
                                           {
                                               "type": "table",
                                               "columns": [
                                                   { "name": "KPI", "width": "35%" },
                                                   { "name": "Target", "width": "16%", "alignment": "right" },
                                                   { "name": "Actual", "width": "16%", "alignment": "right" },
                                                   { "name": "Status", "width": "16%", "alignment": "center" },
                                                   { "name": "Trend", "width": "17%", "alignment": "center" }
                                               ],
                                               "rows": [
                                                   { "cells": ["Monthly Recurring Revenue", "$4.2M", "$4.5M", "Exceeded", "Up"] },
                                                   { "cells": ["Customer Acquisition Cost", "$1,200", "$980", "Exceeded", "Down (good)"] },
                                                   { "cells": ["Lifetime Value (LTV)", "$45,000", "$48,200", "Exceeded", "Up"] },
                                                   { "cells": ["Churn Rate", "< 3.0%", "2.4%", "Exceeded", "Down (good)"] },
                                                   { "cells": ["NPS Score", "> 70", "82", "Exceeded", "Up"] },
                                                   { "cells": ["Sprint Velocity", "85 pts", "92 pts", "Exceeded", "Up"] },
                                                   { "cells": ["Uptime SLA", "99.9%", "99.97%", "Exceeded", "Stable"] },
                                                   { "cells": ["Mean Time to Resolution", "< 4h", "2.8h", "Exceeded", "Down (good)"] }
                                               ],
                                               "headerStyle": { "backgroundColor": "#0f3460", "color": "#FFFFFF", "fontWeight": "bold" },
                                               "alternateRowColors": true,
                                               "alternateColor": "#EBF5FB",
                                               "borders": { "width": "0.5pt", "color": "#B0C4DE" }
                                           },
                                           { "type": "text", "text": "" },
                                           {
                                               "type": "paragraph",
                                               "content": "All eight tracked KPIs exceeded their targets for Q4. Notably, Customer Acquisition Cost dropped 18% below target due to improved marketing efficiency, and system uptime exceeded the 99.9% SLA target at 99.97%. The engineering team's sprint velocity increased by 8% compared to Q3.",
                                               "style": "body"
                                           }
                                       ]
                                   },
                                   "footer": {
                                       "height": "12mm",
                                       "elements": [
                                           { "type": "text", "text": "Page {pageNumber} of {pageCount}  |  Confidential", "style": "caption" }
                                       ]
                                   }
                               },
                               {
                                   "header": {
                                       "height": "12mm",
                                       "elements": [
                                           { "type": "text", "text": "Q4 2024 Quarterly Report  |  Confidential", "fontSize": 8, "color": "#AAAAAA" }
                                       ]
                                   },
                                   "body": {
                                       "elements": [
                                           { "type": "text", "text": "4. Strategic Outlook — Q1 2025", "style": "h1" },
                                           { "type": "line", "color": "#1a1a2e", "strokeWidth": "1.5pt" },
                                           { "type": "text", "text": "" },
                                           {
                                               "type": "paragraph",
                                               "content": "Looking ahead to Q1 2025, the company is well-positioned for continued growth. Key strategic initiatives include the launch of the AI-powered analytics module (Project Aurora), expansion into the APAC market with a Singapore office opening in February, and the rollout of the new enterprise pricing tier targeting Fortune 500 companies.",
                                               "style": "body"
                                           },
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "4.1 Priority Initiatives", "style": "h2" },
                                           {
                                               "type": "table",
                                               "columns": [
                                                   { "name": "Initiative", "width": "35%" },
                                                   { "name": "Owner", "width": "20%" },
                                                   { "name": "Timeline", "width": "20%" },
                                                   { "name": "Investment", "width": "25%", "alignment": "right" }
                                               ],
                                               "rows": [
                                                   { "cells": ["Project Aurora (AI Analytics)", "CTO Office", "Q1-Q2 2025", "$2,400,000"] },
                                                   { "cells": ["APAC Market Entry", "VP Sales", "Feb 2025", "$1,800,000"] },
                                                   { "cells": ["Enterprise Tier Launch", "Product", "Mar 2025", "$600,000"] },
                                                   { "cells": ["SOC 2 Type II Certification", "Security", "Q1 2025", "$350,000"] },
                                                   { "cells": ["Mobile App v2.0", "Engineering", "Q1-Q2 2025", "$900,000"] }
                                               ],
                                               "headerStyle": { "backgroundColor": "#1a1a2e", "color": "#FFFFFF", "fontWeight": "bold" },
                                               "alternateRowColors": true,
                                               "alternateColor": "#F8F9FA",
                                               "borders": { "width": "0.5pt", "color": "#DEE2E6" }
                                           },
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "" },
                                           { "type": "rectangle", "fillColor": "#F0F4F8", "width": "170mm", "height": "40mm", "strokeColor": "#B0C4DE", "strokeWidth": "0.5pt" },
                                           { "type": "text", "text": "Summary", "style": "h2" },
                                           {
                                               "type": "paragraph",
                                               "content": "Q4 2024 exceeded expectations across all major metrics. Revenue growth of 23% YoY, combined with significant cost savings from the Platform 2.0 migration, positions the company for a strong FY2025. The Board has approved the Q1 2025 strategic investment plan totaling $6.05M, with projected ROI of 280% over 18 months.",
                                               "style": "body"
                                           },
                                           { "type": "text", "text": "" },
                                           { "type": "text", "text": "" },
                                           { "type": "rectangle", "fillColor": "#1a1a2e", "width": "170mm", "height": "1mm" },
                                           { "type": "text", "text": "End of Report", "fontSize": 10, "alignment": "center", "color": "#888888" }
                                       ]
                                   },
                                   "footer": {
                                       "height": "12mm",
                                       "elements": [
                                           { "type": "text", "text": "Page {pageNumber} of {pageCount}  |  Confidential", "style": "caption" }
                                       ]
                                   }
                               }
                           ]
                       }
                       """;

        GenerateAndAssert(template, "04-quarterly-report.pdf");
    }

    // ── 5. Tables Showcase ──────────────────────────────────────────────────

    [Fact]
    public void Generate_TablesShowcase()
    {
        var template = """
                       {
                           "metadata": { "title": "Tables Showcase" },
                           "styles": {
                               "h1": { "fontSize": 22, "fontWeight": "bold", "color": "#2c3e50" },
                               "h2": { "fontSize": 14, "fontWeight": "bold", "color": "#34495e" },
                               "body": { "fontSize": 10, "color": "#333333" }
                           },
                           "pages": [{
                               "body": {
                                   "elements": [
                                       { "type": "text", "text": "Table Styles Showcase", "style": "h1" },
                                       { "type": "line", "color": "#2c3e50", "strokeWidth": "2pt" },
                                       { "type": "text", "text": "" },

                                       { "type": "text", "text": "Dark Header Table with Alternating Rows", "style": "h2" },
                                       {
                                           "type": "table",
                                           "columns": [
                                               { "name": "Employee", "width": "25%" },
                                               { "name": "Department", "width": "20%" },
                                               { "name": "Role", "width": "25%" },
                                               { "name": "Salary", "width": "15%", "alignment": "right" },
                                               { "name": "Start Date", "width": "15%", "alignment": "center" }
                                           ],
                                           "rows": [
                                               { "cells": ["Alice Johnson", "Engineering", "Senior Developer", "$145,000", "2019-03"] },
                                               { "cells": ["Bob Smith", "Marketing", "Campaign Manager", "$95,000", "2020-07"] },
                                               { "cells": ["Carol Davis", "Engineering", "Tech Lead", "$165,000", "2018-01"] },
                                               { "cells": ["David Wilson", "Sales", "Account Executive", "$85,000", "2021-04"] },
                                               { "cells": ["Eve Martinez", "Design", "UX Lead", "$130,000", "2019-11"] },
                                               { "cells": ["Frank Lee", "Engineering", "DevOps Engineer", "$140,000", "2020-02"] },
                                               { "cells": ["Grace Kim", "Product", "Product Manager", "$135,000", "2019-06"] }
                                           ],
                                           "headerStyle": { "backgroundColor": "#2c3e50", "color": "#FFFFFF", "fontWeight": "bold" },
                                           "alternateRowColors": true,
                                           "alternateColor": "#ECF0F1",
                                           "borders": { "width": "0.5pt", "color": "#BDC3C7" }
                                       },

                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "Blue Header Table — Product Catalog", "style": "h2" },
                                       {
                                           "type": "table",
                                           "columns": [
                                               { "name": "SKU", "width": "15%" },
                                               { "name": "Product Name", "width": "30%" },
                                               { "name": "Category", "width": "20%" },
                                               { "name": "Price", "width": "15%", "alignment": "right" },
                                               { "name": "In Stock", "width": "20%", "alignment": "center" }
                                           ],
                                           "rows": [
                                               { "cells": ["WDG-001", "Premium Widget Pro", "Electronics", "$49.99", "Yes (342)"] },
                                               { "cells": ["WDG-002", "Widget Lite", "Electronics", "$24.99", "Yes (1,205)"] },
                                               { "cells": ["GAD-001", "SmartGadget X", "Smart Home", "$129.99", "Yes (89)"] },
                                               { "cells": ["GAD-002", "SmartGadget Mini", "Smart Home", "$79.99", "Low (12)"] },
                                               { "cells": ["ACC-001", "Universal Adapter", "Accessories", "$14.99", "Yes (5,000)"] },
                                               { "cells": ["ACC-002", "Premium Cable (6ft)", "Accessories", "$19.99", "Out of Stock"] }
                                           ],
                                           "headerStyle": { "backgroundColor": "#2980b9", "color": "#FFFFFF", "fontWeight": "bold" },
                                           "alternateRowColors": true,
                                           "alternateColor": "#EBF5FB",
                                           "borders": { "width": "0.5pt", "color": "#85C1E9" }
                                       },

                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "Green Header Table — Server Status", "style": "h2" },
                                       {
                                           "type": "table",
                                           "columns": [
                                               { "name": "Server", "width": "20%" },
                                               { "name": "Region", "width": "15%" },
                                               { "name": "Status", "width": "15%", "alignment": "center" },
                                               { "name": "CPU", "width": "12%", "alignment": "right" },
                                               { "name": "Memory", "width": "13%", "alignment": "right" },
                                               { "name": "Uptime", "width": "25%", "alignment": "right" }
                                           ],
                                           "rows": [
                                               { "cells": ["prod-web-01", "US-East", "Healthy", "34%", "68%", "99.99% (142 days)"] },
                                               { "cells": ["prod-web-02", "US-West", "Healthy", "28%", "55%", "99.98% (89 days)"] },
                                               { "cells": ["prod-api-01", "EU-West", "Healthy", "62%", "71%", "99.97% (201 days)"] },
                                               { "cells": ["prod-db-01", "US-East", "Warning", "78%", "89%", "99.95% (45 days)"] },
                                               { "cells": ["prod-cache-01", "US-East", "Healthy", "15%", "92%", "100% (201 days)"] },
                                               { "cells": ["staging-01", "US-East", "Degraded", "91%", "95%", "98.5% (12 days)"] }
                                           ],
                                           "headerStyle": { "backgroundColor": "#27ae60", "color": "#FFFFFF", "fontWeight": "bold" },
                                           "alternateRowColors": true,
                                           "alternateColor": "#EAFAF1",
                                           "borders": { "width": "0.5pt", "color": "#82E0AA" }
                                       }
                                   ]
                               }
                           }]
                       }
                       """;

        GenerateAndAssert(template, "05-tables-showcase.pdf");
    }

    // ── 6. Shapes & Lines ───────────────────────────────────────────────────

    [Fact]
    public void Generate_ShapesAndLines()
    {
        var template = """
                       {
                           "metadata": { "title": "Shapes & Lines Demo" },
                           "styles": {
                               "h1": { "fontSize": 22, "fontWeight": "bold", "color": "#2c3e50" },
                               "h2": { "fontSize": 14, "fontWeight": "bold", "color": "#34495e" }
                           },
                           "pages": [{
                               "body": {
                                   "elements": [
                                       { "type": "text", "text": "Shapes & Lines Demo", "style": "h1" },
                                       { "type": "text", "text": "" },

                                       { "type": "text", "text": "Filled Rectangles", "style": "h2" },
                                       { "type": "rectangle", "fillColor": "#3498db", "width": "170mm", "height": "15mm" },
                                       { "type": "rectangle", "fillColor": "#e74c3c", "width": "130mm", "height": "12mm" },
                                       { "type": "rectangle", "fillColor": "#2ecc71", "width": "90mm", "height": "10mm" },
                                       { "type": "rectangle", "fillColor": "#f39c12", "width": "50mm", "height": "8mm" },
                                       { "type": "text", "text": "" },

                                       { "type": "text", "text": "Stroked Rectangle with Corner Radius", "style": "h2" },
                                       { "type": "rectangle", "fillColor": "#F8F9FA", "strokeColor": "#3498db", "strokeWidth": "2pt", "width": "170mm", "height": "25mm", "cornerRadius": "5mm" },
                                       { "type": "text", "text": "" },

                                       { "type": "text", "text": "Bordered Boxes", "style": "h2" },
                                       { "type": "rectangle", "strokeColor": "#e74c3c", "strokeWidth": "2pt", "width": "170mm", "height": "20mm" },
                                       { "type": "rectangle", "strokeColor": "#3498db", "strokeWidth": "1pt", "width": "170mm", "height": "20mm" },
                                       { "type": "text", "text": "" },

                                       { "type": "text", "text": "Line Styles", "style": "h2" },
                                       { "type": "line", "color": "#2c3e50", "strokeWidth": "3pt" },
                                       { "type": "text", "text": "Thick solid line (3pt)", "fontSize": 8, "color": "#888888" },
                                       { "type": "line", "color": "#e74c3c", "strokeWidth": "1pt" },
                                       { "type": "text", "text": "Medium red line (1pt)", "fontSize": 8, "color": "#888888" },
                                       { "type": "line", "color": "#3498db", "strokeWidth": "0.5pt" },
                                       { "type": "text", "text": "Thin blue line (0.5pt)", "fontSize": 8, "color": "#888888" },
                                       { "type": "line", "color": "#888888", "strokeWidth": "1pt", "dashPattern": "6,3" },
                                       { "type": "text", "text": "Dashed line (6,3 pattern)", "fontSize": 8, "color": "#888888" },
                                       { "type": "line", "color": "#2ecc71", "strokeWidth": "1pt", "dashPattern": "2,2" },
                                       { "type": "text", "text": "Dotted green line (2,2 pattern)", "fontSize": 8, "color": "#888888" },
                                       { "type": "line", "color": "#9b59b6", "strokeWidth": "1.5pt", "dashPattern": "8,3,2,3" },
                                       { "type": "text", "text": "Dash-dot purple line (8,3,2,3 pattern)", "fontSize": 8, "color": "#888888" }
                                   ]
                               }
                           }]
                       }
                       """;

        GenerateAndAssert(template, "06-shapes-and-lines.pdf");
    }

    // ── 7. Data-Bound Letter ────────────────────────────────────────────────

    [Fact]
    public void Generate_DataBoundLetter()
    {
        var template = """
                       {
                           "metadata": { "title": "Offer Letter" },
                           "settings": {
                               "pageSize": "Letter",
                               "margins": { "top": "25mm", "bottom": "25mm", "left": "25mm", "right": "25mm" }
                           },
                           "pages": [{
                               "header": {
                                   "height": "30mm",
                                   "elements": [
                                       { "type": "text", "text": "${company.name}", "fontSize": 22, "fontWeight": "bold", "color": "#1B4F72" },
                                       { "type": "text", "text": "${company.tagline}", "fontSize": 10, "color": "#85929E" },
                                       { "type": "line", "color": "#1B4F72", "strokeWidth": "1.5pt" }
                                   ]
                               },
                               "body": {
                                   "elements": [
                                       { "type": "text", "text": "${letter.date}", "fontSize": 11, "alignment": "right" },
                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "Dear ${candidate.name},", "fontSize": 12 },
                                       { "type": "text", "text": "" },
                                       {
                                           "type": "paragraph",
                                           "content": "We are thrilled to extend an offer for the position of ${offer.position} at ${company.name}. After a thorough evaluation process, we were deeply impressed by your skills, experience, and the unique perspective you would bring to our team.",
                                           "fontSize": 11,
                                           "lineHeight": 1.6
                                       },
                                       { "type": "text", "text": "" },
                                       {
                                           "type": "paragraph",
                                           "content": "We believe your background in ${candidate.expertise} aligns perfectly with our mission to ${company.mission}. Below are the details of your offer:",
                                           "fontSize": 11,
                                           "lineHeight": 1.6
                                       },
                                       { "type": "text", "text": "" },
                                       { "type": "rectangle", "fillColor": "#EBF5FB", "width": "155mm", "height": "60mm", "strokeColor": "#85C1E9", "strokeWidth": "0.5pt", "cornerRadius": "3mm" },
                                       {
                                           "type": "table",
                                           "columns": [
                                               { "name": "Detail", "width": "40%", "alignment": "left" },
                                               { "name": "Value", "width": "60%", "alignment": "left" }
                                           ],
                                           "rows": [
                                               { "cells": ["Position", "${offer.position}"] },
                                               { "cells": ["Department", "${offer.department}"] },
                                               { "cells": ["Start Date", "${offer.startDate}"] },
                                               { "cells": ["Annual Salary", "${offer.salary}"] },
                                               { "cells": ["Signing Bonus", "${offer.signingBonus}"] },
                                               { "cells": ["Equity Grant", "${offer.equity}"] },
                                               { "cells": ["PTO", "${offer.pto}"] },
                                               { "cells": ["Reports To", "${offer.reportsTo}"] }
                                           ],
                                           "headerStyle": { "backgroundColor": "#1B4F72", "color": "#FFFFFF", "fontWeight": "bold" },
                                           "showHeader": false,
                                           "borders": { "width": "0.5pt", "color": "#D4E6F1" }
                                       },
                                       { "type": "text", "text": "" },
                                       {
                                           "type": "paragraph",
                                           "content": "This offer is contingent upon successful completion of a background check and is valid until ${offer.expiryDate}. Please sign and return this letter to confirm your acceptance.",
                                           "fontSize": 11,
                                           "lineHeight": 1.6
                                       },
                                       { "type": "text", "text": "" },
                                       {
                                           "type": "paragraph",
                                           "content": "We are very excited about the possibility of you joining our team and look forward to the contributions you will make. If you have any questions, please don't hesitate to reach out.",
                                           "fontSize": 11,
                                           "lineHeight": 1.6
                                       },
                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "Warm regards,", "fontSize": 11 },
                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "${sender.name}", "fontSize": 12, "fontWeight": "bold" },
                                       { "type": "text", "text": "${sender.title}", "fontSize": 11, "color": "#555555" },
                                       { "type": "text", "text": "${company.name}", "fontSize": 11, "color": "#555555" }
                                   ]
                               },
                               "footer": {
                                   "height": "15mm",
                                   "elements": [
                                       { "type": "line", "color": "#D5D8DC", "strokeWidth": "0.5pt" },
                                       { "type": "text", "text": "${company.address}  |  ${company.phone}  |  ${company.website}", "fontSize": 8, "color": "#999999", "alignment": "center" }
                                   ]
                               }
                           }]
                       }
                       """;

        var data = """
                   {
                       "company": {
                           "name": "NovaTech Solutions",
                           "tagline": "Building the future of enterprise software",
                           "mission": "revolutionize how businesses leverage data and AI",
                           "address": "500 Technology Park, Suite 200, Austin, TX 78701",
                           "phone": "(512) 555-0200",
                           "website": "www.novatech.io"
                       },
                       "letter": { "date": "March 13, 2026" },
                       "candidate": {
                           "name": "Sarah Chen",
                           "expertise": "distributed systems and cloud architecture"
                       },
                       "offer": {
                           "position": "Principal Software Engineer",
                           "department": "Platform Engineering",
                           "startDate": "April 14, 2026",
                           "salary": "$195,000",
                           "signingBonus": "$25,000",
                           "equity": "15,000 RSUs (4-year vest, 1-year cliff)",
                           "pto": "Unlimited PTO + 12 holidays",
                           "reportsTo": "VP of Engineering — Michael Torres",
                           "expiryDate": "March 27, 2026"
                       },
                       "sender": {
                           "name": "Jennifer Walsh",
                           "title": "Director of Talent Acquisition"
                       }
                   }
                   """;

        GenerateAndAssert(template, "07-offer-letter.pdf", data);
    }

    // ── 8. Landscape & Different Page Sizes ─────────────────────────────────

    [Fact]
    public void Generate_LandscapeLayout()
    {
        var template = """
                       {
                           "metadata": { "title": "Landscape Dashboard" },
                           "settings": {
                               "pageSize": "A4",
                               "orientation": "Landscape",
                               "margins": { "top": "15mm", "bottom": "15mm", "left": "15mm", "right": "15mm" }
                           },
                           "styles": {
                               "dashTitle": { "fontSize": 20, "fontWeight": "bold", "color": "#FFFFFF" },
                               "metric": { "fontSize": 28, "fontWeight": "bold", "color": "#2c3e50" },
                               "metricLabel": { "fontSize": 10, "color": "#7f8c8d" }
                           },
                           "pages": [{
                               "body": {
                                   "elements": [
                                       { "type": "rectangle", "fillColor": "#2c3e50", "width": "267mm", "height": "20mm" },
                                       { "type": "text", "text": "  Executive Dashboard — March 2026", "style": "dashTitle" },
                                       { "type": "text", "text": "" },

                                       { "type": "text", "text": "$4.5M", "style": "metric" },
                                       { "type": "text", "text": "Monthly Recurring Revenue", "style": "metricLabel" },
                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "15,200", "style": "metric" },
                                       { "type": "text", "text": "Active Customers", "style": "metricLabel" },
                                       { "type": "text", "text": "" },

                                       { "type": "text", "text": "Regional Performance", "fontSize": 14, "fontWeight": "bold", "color": "#2c3e50" },
                                       {
                                           "type": "table",
                                           "columns": [
                                               { "name": "Region", "width": "15%" },
                                               { "name": "Revenue", "width": "14%", "alignment": "right" },
                                               { "name": "Customers", "width": "12%", "alignment": "right" },
                                               { "name": "Growth", "width": "10%", "alignment": "right" },
                                               { "name": "Avg Deal Size", "width": "13%", "alignment": "right" },
                                               { "name": "Win Rate", "width": "10%", "alignment": "right" },
                                               { "name": "Pipeline", "width": "13%", "alignment": "right" },
                                               { "name": "Top Product", "width": "13%" }
                                           ],
                                           "rows": [
                                               { "cells": ["North America", "$1.8M", "6,200", "+24%", "$48K", "38%", "$5.2M", "Enterprise Suite"] },
                                               { "cells": ["Europe (EMEA)", "$1.2M", "4,100", "+18%", "$42K", "35%", "$3.8M", "Cloud Platform"] },
                                               { "cells": ["Asia-Pacific", "$0.9M", "3,400", "+32%", "$38K", "41%", "$2.9M", "API Gateway"] },
                                               { "cells": ["Latin America", "$0.4M", "1,100", "+45%", "$28K", "33%", "$1.4M", "Starter Plan"] },
                                               { "cells": ["Middle East", "$0.2M", "400", "+52%", "$35K", "29%", "$0.8M", "Enterprise Suite"] }
                                           ],
                                           "headerStyle": { "backgroundColor": "#2c3e50", "color": "#FFFFFF", "fontWeight": "bold" },
                                           "alternateRowColors": true,
                                           "alternateColor": "#F2F3F4",
                                           "borders": { "width": "0.5pt", "color": "#BDC3C7" }
                                       },

                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "Top Deals in Pipeline", "fontSize": 14, "fontWeight": "bold", "color": "#2c3e50" },
                                       {
                                           "type": "table",
                                           "columns": [
                                               { "name": "Company", "width": "20%" },
                                               { "name": "Deal Value", "width": "15%", "alignment": "right" },
                                               { "name": "Stage", "width": "15%", "alignment": "center" },
                                               { "name": "Probability", "width": "12%", "alignment": "right" },
                                               { "name": "Owner", "width": "15%" },
                                               { "name": "Expected Close", "width": "13%", "alignment": "center" },
                                               { "name": "Product", "width": "10%" }
                                           ],
                                           "rows": [
                                               { "cells": ["GlobalTech Corp", "$420,000", "Negotiation", "85%", "James Park", "Mar 2026", "Enterprise"] },
                                               { "cells": ["Meridian Group", "$380,000", "Proposal", "70%", "Lisa Chen", "Apr 2026", "Platform"] },
                                               { "cells": ["Atlas Industries", "$295,000", "Demo", "55%", "Ryan O'Brien", "Apr 2026", "Enterprise"] },
                                               { "cells": ["Summit Financial", "$250,000", "Negotiation", "90%", "Maria Santos", "Mar 2026", "API GW"] }
                                           ],
                                           "headerStyle": { "backgroundColor": "#1a5276", "color": "#FFFFFF", "fontWeight": "bold" },
                                           "alternateRowColors": true,
                                           "alternateColor": "#EBF5FB",
                                           "borders": { "width": "0.5pt", "color": "#85C1E9" }
                                       }
                                   ]
                               }
                           }]
                       }
                       """;

        GenerateAndAssert(template, "08-landscape-dashboard.pdf");
    }

    // ── 9. Paragraph Wrapping Stress Test ───────────────────────────────────

    [Fact]
    public void Generate_ParagraphWrapping()
    {
        var template = """
                       {
                           "metadata": { "title": "Paragraph Wrapping Test" },
                           "settings": { "pageSize": "A4" },
                           "styles": {
                               "h1": { "fontSize": 20, "fontWeight": "bold", "color": "#2c3e50" },
                               "p": { "fontSize": 11, "color": "#333333", "lineHeight": 1.6 }
                           },
                           "pages": [{
                               "body": {
                                   "elements": [
                                       { "type": "text", "text": "Long-Form Content Test", "style": "h1" },
                                       { "type": "line", "color": "#2c3e50", "strokeWidth": "1pt" },
                                       { "type": "text", "text": "" },
                                       {
                                           "type": "paragraph",
                                           "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                                           "style": "p"
                                       },
                                       { "type": "text", "text": "" },
                                       {
                                           "type": "paragraph",
                                           "content": "Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris. Integer in mauris eu nibh euismod gravida. Duis ac tellus et risus vulputate vehicula. Donec lobortis risus a elit. Etiam tempor. Ut ullamcorper, ligula ut dictum pharetra, nisi nunc fringilla magna, in commodo elit erat nec turpis. Ut pharetra augue nec augue.",
                                           "style": "p"
                                       },
                                       { "type": "text", "text": "" },
                                       {
                                           "type": "paragraph",
                                           "content": "Nam dui ligula, fringilla a, euismod sodales, sollicitudin vel, wisi. Morbi auctor lorem non justo. Nam lacus libero, pretium at, lobortis vitae, ultricies et, tellus. Donec aliquet, tortor sed accumsan bibendum, erat ligula aliquet magna, vitae ornare odio metus a mi. Morbi ac orci et nisl hendrerit mollis. Suspendisse ut massa. Cras nec ante. In justo. Nullam cursus lacinia erat. Praesent blandit laoreet nibh. Fusce convallis metus id felis luctus adipiscing.",
                                           "style": "p"
                                       },
                                       { "type": "text", "text": "" },
                                       { "type": "text", "text": "Narrow Column Test (100mm wide)", "style": "h1" },
                                       { "type": "line", "color": "#2c3e50", "strokeWidth": "1pt" },
                                       {
                                           "type": "paragraph",
                                           "content": "This paragraph has an explicit width of 100mm. Text should wrap within this narrower constraint. This tests that the word-wrapping algorithm correctly handles a width smaller than the page content area. Each line should be no wider than 100mm.",
                                           "fontSize": 11,
                                           "lineHeight": 1.5,
                                           "width": "100mm"
                                       }
                                   ]
                               }
                           }]
                       }
                       """;

        GenerateAndAssert(template, "09-paragraph-wrapping.pdf");
    }

    // ── 10. All Elements Combined ───────────────────────────────────────────

    [Fact]
    public void Generate_AllElementsCombined()
    {
        var template = """
                       {
                           "metadata": { "title": "All Elements Demo", "author": "R4PDF" },
                           "settings": {
                               "pageSize": "A4",
                               "margins": { "top": "20mm", "bottom": "20mm", "left": "20mm", "right": "20mm" }
                           },
                           "styles": {
                               "title": { "fontSize": 26, "fontWeight": "bold", "color": "#1B2631" },
                               "section": { "fontSize": 16, "fontWeight": "bold", "color": "#2E4053" },
                               "body": { "fontSize": 11, "color": "#2C3E50", "lineHeight": 1.5 },
                               "small": { "fontSize": 9, "color": "#7F8C8D" }
                           },
                           "pages": [{
                               "header": {
                                   "height": "18mm",
                                   "elements": [
                                       { "type": "rectangle", "fillColor": "#1B2631", "width": "170mm", "height": "12mm" },
                                       { "type": "text", "text": "  R4PDF — Element Showcase", "fontSize": 14, "fontWeight": "bold", "color": "#FFFFFF" }
                                   ]
                               },
                               "body": {
                                   "elements": [
                                       { "type": "text", "text": "All Supported Elements", "style": "title" },
                                       { "type": "line", "color": "#1B2631", "strokeWidth": "2pt" },
                                       { "type": "text", "text": "" },

                                       { "type": "text", "text": "1. Text Element", "style": "section" },
                                       { "type": "text", "text": "Regular text — useful for titles, labels, and single-line content.", "fontSize": 11 },
                                       { "type": "text", "text": "Bold text", "fontSize": 11, "fontWeight": "bold" },
                                       { "type": "text", "text": "Colored text", "fontSize": 11, "color": "#e74c3c" },
                                       { "type": "text", "text": "Right-aligned text", "fontSize": 11, "alignment": "right" },
                                       { "type": "text", "text": "" },

                                       { "type": "text", "text": "2. Paragraph Element", "style": "section" },
                                       {
                                           "type": "paragraph",
                                           "content": "Paragraphs automatically wrap text across multiple lines. They support configurable line height, spacing before and after, and text alignment. This is ideal for body content, descriptions, and any text block that may exceed one line.",
                                           "style": "body"
                                       },
                                       { "type": "text", "text": "" },

                                       { "type": "text", "text": "3. Table Element", "style": "section" },
                                       {
                                           "type": "table",
                                           "columns": [
                                               { "name": "Feature", "width": "40%" },
                                               { "name": "Status", "width": "30%", "alignment": "center" },
                                               { "name": "Version", "width": "30%", "alignment": "right" }
                                           ],
                                           "rows": [
                                               { "cells": ["Text rendering", "Supported", "1.0"] },
                                               { "cells": ["Paragraph wrapping", "Supported", "1.0"] },
                                               { "cells": ["Table generation", "Supported", "1.0"] },
                                               { "cells": ["Image embedding", "Supported", "1.0"] },
                                               { "cells": ["Line drawing", "Supported", "1.0"] },
                                               { "cells": ["Rectangle/shapes", "Supported", "1.0"] }
                                           ],
                                           "headerStyle": { "backgroundColor": "#2E4053", "color": "#FFFFFF", "fontWeight": "bold" },
                                           "alternateRowColors": true,
                                           "alternateColor": "#F4F6F7",
                                           "borders": { "width": "0.5pt", "color": "#ABB2B9" }
                                       },
                                       { "type": "text", "text": "" },

                                       { "type": "text", "text": "4. Line Element", "style": "section" },
                                       { "type": "line", "color": "#1B2631", "strokeWidth": "2pt" },
                                       { "type": "text", "text": "Solid thick", "style": "small" },
                                       { "type": "line", "color": "#3498db", "strokeWidth": "1pt", "dashPattern": "6,3" },
                                       { "type": "text", "text": "Dashed blue", "style": "small" },
                                       { "type": "line", "color": "#e74c3c", "strokeWidth": "1pt", "dashPattern": "2,2" },
                                       { "type": "text", "text": "Dotted red", "style": "small" },
                                       { "type": "text", "text": "" },

                                       { "type": "text", "text": "5. Rectangle Element", "style": "section" },
                                       { "type": "rectangle", "fillColor": "#D5F5E3", "strokeColor": "#27AE60", "strokeWidth": "1pt", "width": "170mm", "height": "15mm", "cornerRadius": "3mm" },
                                       { "type": "text", "text": "Rounded green box with border", "style": "small" },
                                       { "type": "rectangle", "fillColor": "#FADBD8", "strokeColor": "#E74C3C", "strokeWidth": "1pt", "width": "170mm", "height": "15mm" },
                                       { "type": "text", "text": "Red box (no corner radius)", "style": "small" },
                                       { "type": "rectangle", "fillColor": "#D6EAF8", "width": "170mm", "height": "15mm" },
                                       { "type": "text", "text": "Blue fill only (no border)", "style": "small" }
                                   ]
                               },
                               "footer": {
                                   "height": "15mm",
                                   "elements": [
                                       { "type": "line", "color": "#BDC3C7", "strokeWidth": "0.5pt" },
                                       { "type": "text", "text": "Generated by R4PDF v1.0  |  Page {pageNumber} of {pageCount}", "style": "small", "alignment": "center" }
                                   ]
                               }
                           }]
                       }
                       """;

        GenerateAndAssert(template, "10-all-elements.pdf");
    }
}